driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: vc6
    run_list:
      - recipe[vcruntime::vc6]
  - name: vc9
    run_list:
      - recipe[vcruntime::vc9]
  - name: vc10
    run_list:
      - recipe[vcruntime::vc10]
  - name: vc11
    run_list:
      - recipe[vcruntime::vc11]
  - name: vc12
    run_list:
      - recipe[vcruntime::vc12]
  - name: vc14
    run_list:
      - recipe[vcruntime::vc14]
